from typing import List, Dict, Any

SYMPTOM_DISEASE_MAP: List[Dict[str, Any]] = [
    {
        "disease": "Flu (Influenza)",
        "keywords": ["fever", "cough", "body ache", "fatigue", "chills", "sore throat", "runny nose"],
        "severity": "Moderate",
        "recommendation": "Rest, stay hydrated, take acetaminophen for fever. Consult a doctor if symptoms persist beyond 3 days.",
        "specialist": "General Physician",
    },
    {
        "disease": "Common Cold",
        "keywords": ["runny nose", "sneezing", "congestion", "mild cough", "sore throat", "mild headache"],
        "severity": "Mild",
        "recommendation": "Rest, drink warm fluids, use saline nasal spray. Most colds resolve in 7-10 days.",
        "specialist": "General Physician",
    },
    {
        "disease": "Migraine",
        "keywords": ["headache", "nausea", "light sensitivity", "blurred vision", "throbbing pain"],
        "severity": "Moderate",
        "recommendation": "Rest in a dark quiet room, apply cold compress, stay hydrated. Consider OTC pain relievers like ibuprofen.",
        "specialist": "Neurologist",
    },
    {
        "disease": "Malaria",
        "keywords": ["fever", "chills", "sweating", "headache", "nausea", "muscle pain", "fatigue"],
        "severity": "Severe",
        "recommendation": "Seek immediate medical attention. Malaria requires prescription antimalarial medication. Do not self-medicate.",
        "specialist": "Infectious Disease Specialist",
    },
    {
        "disease": "Food Poisoning",
        "keywords": ["nausea", "vomiting", "diarrhea", "stomach cramps", "fever", "dehydration"],
        "severity": "Moderate",
        "recommendation": "Stay hydrated with oral rehydration solution. Eat bland foods. Seek medical help if symptoms persist beyond 48 hours.",
        "specialist": "Gastroenterologist",
    },
    {
        "disease": "Allergic Reaction",
        "keywords": ["sneezing", "rash", "itching", "hives", "swelling", "watery eyes", "runny nose"],
        "severity": "Mild",
        "recommendation": "Take antihistamines (like cetirizine). Avoid known allergens. Seek emergency care if breathing difficulty occurs.",
        "specialist": "Allergist",
    },
    {
        "disease": "Pneumonia",
        "keywords": ["fever", "cough with phlegm", "chest pain", "shortness of breath", "fatigue", "sweating"],
        "severity": "Severe",
        "recommendation": "Seek immediate medical attention. Pneumonia requires antibiotic treatment. Do not delay visiting a doctor.",
        "specialist": "Pulmonologist",
    },
    {
        "disease": "COVID-19",
        "keywords": ["fever", "cough", "loss of taste", "loss of smell", "fatigue", "shortness of breath", "sore throat"],
        "severity": "Moderate",
        "recommendation": "Isolate immediately. Rest and monitor oxygen levels. Seek emergency care if breathing becomes difficult.",
        "specialist": "General Physician",
    },
    {
        "disease": "Tension Headache",
        "keywords": ["headache", "neck pain", "scalp tenderness", "pressure around forehead"],
        "severity": "Mild",
        "recommendation": "Rest, apply heat to neck and shoulders, take OTC pain relievers like ibuprofen or acetaminophen.",
        "specialist": "General Physician",
    },
    {
        "disease": "Gastritis",
        "keywords": ["stomach pain", "nausea", "bloating", "indigestion", "burning sensation", "loss of appetite"],
        "severity": "Mild",
        "recommendation": "Eat small bland meals, avoid spicy food, take antacids. Consult a doctor if pain persists.",
        "specialist": "Gastroenterologist",
    },
    {
        "disease": "Urinary Tract Infection (UTI)",
        "keywords": ["burning urination", "frequent urination", "pelvic pain", "cloudy urine", "fever"],
        "severity": "Moderate",
        "recommendation": "Drink plenty of water, avoid irritants. UTI requires antibiotic treatment — consult a doctor.",
        "specialist": "Urologist",
    },
    {
        "disease": "Dengue Fever",
        "keywords": ["high fever", "severe headache", "pain behind eyes", "joint pain", "muscle pain", "rash", "fatigue"],
        "severity": "Severe",
        "recommendation": "Seek immediate medical attention. Stay hydrated, take rest. Avoid NSAIDs like ibuprofen. Use acetaminophen for fever.",
        "specialist": "Infectious Disease Specialist",
    },
    {
        "disease": "Anxiety Disorder",
        "keywords": ["restlessness", "rapid heartbeat", "sweating", "trembling", "fatigue", "difficulty concentrating"],
        "severity": "Moderate",
        "recommendation": "Practice deep breathing and relaxation techniques. Consider counseling or therapy. Consult a mental health professional.",
        "specialist": "Psychiatrist",
    },
    {
        "disease": "Hypertension (High Blood Pressure)",
        "keywords": ["headache", "dizziness", "blurred vision", "chest pain", "shortness of breath", "nosebleeds"],
        "severity": "Moderate",
        "recommendation": "Monitor blood pressure regularly, reduce salt intake, exercise regularly. Consult a doctor for medication management.",
        "specialist": "Cardiologist",
    },
]
